name: ETL Job
on:
  schedule:
    - cron: '0 * * * *' # Pokreće se na svakih sat vremena
  workflow_dispatch: # Omogućava ti da klikneš "Run" ručno

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run ETL
        env:
          NASA_FIRMS_KEY: ${{ fe0ebf60ed55aa1cd2f70abb9ddb2978 }}
          DB_URL: ${{ postgresql://neondb_owner:npg_RLW9GIzPN8jJ@ep-green-tooth-ab7n0h1e-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require }}
          CLIENT_ID: ${{ 9b08ac2b-a176-44ef-97ec-0f3cb5a8c2b9 }}
          CLIENT_SECRET: ${{ HT0dqu5uCECVf5IgkH1YPYiw4EjS1Ffp }}
          USER: ${{ andjelarajovic01@gmail.com }}
          PASS: ${{ napsapkap }}
        run: python main_worker.py